/* Copyright (C) 2009 Thomas Rampelberg <pyronicide@saunter.org>

 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.

 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/* Model for torrent information.
 */

package org.saunter.swarmstat.model

import net.liftweb.mapper._
import net.liftweb.util.Helpers._
import net.liftweb.util._

import org.saunter.swarmstat.util._

import java.util.Random

class PropperMappedStringIndex[T<:Mapper[T]](
  override val fieldOwner: T, override val maxLen: Int) extends
  MappedStringIndex[T](fieldOwner, maxLen) {
    override def writePermission_? = true
    override def dbAutogenerated_? = false
    override def fieldCreatorString(dbType: DriverType, colName: String) =
      super.fieldCreatorString(dbType, colName) + " NOT NULL "
  }

class SpecialLongIndex[T<:Mapper[T]](theOwner: T) extends MappedLongIndex[T](theOwner) {
  override def writePermission_? = true
  override def dbAutogenerated_? = false
  private var myDirty = false
  override def dirty_? = myDirty
  override def dirty_?(b: Boolean) = { myDirty = b; super.dirty_?(b) }
  override def fieldCreatorString(dbType: DriverType, colName: String) =
    colName + " " + dbType.longColumnType + " NOT NULL "
  override def defaultValue = (new Random).nextLong
}

class Torrent extends KeyedMapper[String, Torrent] {
  def getSingleton = Torrent
  def primaryKeyField = id

  // Fields
  object id extends UUID(this)
  object info_hash extends MappedPoliteString(this, 20)
  object creation extends MappedDateTime(this) {
    override def defaultValue = timeNow
  }
  object name extends MappedPoliteString(this, 128)
  // object sources extends MappedOneToMany(TorrentSource, TorrentSource.torrent) with Owned[TorrentSource]
}

object Torrent extends Torrent with KeyedMetaMapper[String, Torrent]
